// <auto-generated />
using System;
using LessonsBg.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LessonsBg.Core.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221120153748_ChagnesToUserAndSubjectTypes")]
    partial class ChagnesToUserAndSubjectTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFilterBadge", b =>
                {
                    b.Property<Guid>("CoursesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FilterBadgesId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "FilterBadgesId");

                    b.HasIndex("FilterBadgesId");

                    b.ToTable("CourseFilterBadge");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "845d0b5e-2c47-41a9-989d-95afcdb7edac",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5476ce8c-99be-4d94-9e9c-a88f379e0706",
                            Email = "niki_admin@niki.bg",
                            EmailConfirmed = true,
                            FirstName = "Николай",
                            LastName = "Иванов",
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKI_ADMIN@NIKI.BG",
                            NormalizedUserName = "NIKI_ADMIN@NIKI.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEOIcrA37iKHgcv0JX1JW6cZiqgFMFEAB8/p047bL3uws/Z1UE6SCVxldQedr2v6aUQ==",
                            PhoneNumber = "0896782014",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bf5c124d-72eb-4c3b-af06-3c82ff7036e8",
                            TwoFactorEnabled = false,
                            UserName = "niki_admin@niki.bg"
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUserSubject", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ApplicationUserSubject");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUserTraining", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("ApplicationUserTraining");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.BlogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Author ID");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("BlogPost ID");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Blog comment text.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation of the blog commment.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogComments");

                    b.HasComment("Comments under a blog post.");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation of the post.");

                    b.Property<string>("PostText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The post text.");

                    b.Property<string>("PostTextHeadingImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The leading image of the post.");

                    b.Property<string>("PostThumbnailURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The thumbnail image of the post.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("The title of the post.");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasComment("Blog posts.");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Author ID.");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the course.");

                    b.Property<string>("CourseImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Course image.");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Name of the course.");

                    b.Property<int>("CourseTypeId")
                        .HasColumnType("int")
                        .HasComment("Type of the course.");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Phone number to call if you are interested in the course.");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Website link with additional information about the course.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Courses");

                    b.HasComment("Courses");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.CourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Course type.");

                    b.HasKey("Id");

                    b.ToTable("CourseTypes");

                    b.HasComment("Course type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Piano"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Singing"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Dancing"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Microsoft Excel"
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.FilterBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FilterBadgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("FilterBadge type.");

                    b.HasKey("Id");

                    b.ToTable("FilterBadges");

                    b.HasComment("Filter badge that helps show, who is a course appropriate for.");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilterBadgeType = "1-4 Grade"
                        },
                        new
                        {
                            Id = 2,
                            FilterBadgeType = "5-8 Grade"
                        },
                        new
                        {
                            Id = 3,
                            FilterBadgeType = "9-12 Grade"
                        },
                        new
                        {
                            Id = 4,
                            FilterBadgeType = "University Students"
                        },
                        new
                        {
                            Id = 5,
                            FilterBadgeType = "Elderly"
                        },
                        new
                        {
                            Id = 6,
                            FilterBadgeType = "Online"
                        },
                        new
                        {
                            Id = 7,
                            FilterBadgeType = "Onsite"
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("City name.");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("City region.");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasComment("Locations (cities in Bulgaria and their regions).");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Айтос",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Аксаково",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Алфатар",
                            Region = "Силистра"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Антоново",
                            Region = "Търговище"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Априлци",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ардино",
                            Region = "Кърджали"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Асеновград",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ахелой",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ахтопол",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Балчик",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Банкя",
                            Region = "София град"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Банско",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Баня",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Батак",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Батановци",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Белене",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Белица",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Белово",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Белоградчик",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Белослав",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Берковица",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Благоевград",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Бобов дол",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Бобошево",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Божурище",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Бойчиновци",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Болярово",
                            Region = "Ямбол"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Борово",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ботевград",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Брацигово",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Брегово",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Брезник",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Брезово",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Брусарци",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Бургас",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Бухово",
                            Region = "София град"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Българово",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Бяла",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Бяла",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Бяла Слатина",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Бяла Черква",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Варна",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Велики Преслав",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Велико Търново",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Велинград",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ветово",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Ветрен",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Видин",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Враца",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Вълчедръм",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Вълчи дол",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Върбица",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Вършец",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Габрово",
                            Region = "Габрово"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Генерал Тошево",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Главиница",
                            Region = "Силистра"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Глоджево",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Годеч",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Горна Оряховица",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Гоце Делчев",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Грамада",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Гулянци",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Гурково",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Гълъбово",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Две могили",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Дебелец",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Девин",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Девня",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Джебел",
                            Region = "Кърджали"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Димитровград",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Димово",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Добринище",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Добрич",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Долна баня",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Долна Митрополия",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Долна Оряховица",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Долни Дъбник",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Долни чифлик",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Доспат",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Драгоман",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Дряново",
                            Region = "Габрово"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Дулово",
                            Region = "Силистра"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Дунавци",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Дупница",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Дългопол",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Елена",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Елин Пелин",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Елхово",
                            Region = "Ямбол"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Етрополе",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Завет",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Земен",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Златарица",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Златица",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Златоград",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Ивайловград",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Игнатиево",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Искър",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Исперих",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Ихтиман",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Каблешково",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Каварна",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Казанлък",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Калофер",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Камено",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Каолиново",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Карлово",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Карнобат",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Каспичан",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Кермен",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Килифарево",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Китен",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Клисура",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Кнежа",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Козлодуй",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Койнаре",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Копривщица",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Костандово",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Костенец",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Костинброд",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Котел",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Кочериново",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Кресна",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Криводол",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Кричим",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Крумовград",
                            Region = "Кърджали"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Крън",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Кубрат",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Куклен",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Кула",
                            Region = "Видин"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Кърджали",
                            Region = "Кърджали"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Кюстендил",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Левски",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Летница",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Ловеч",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Лозница",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Лом",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Луковит",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Лъки",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Любимец",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Лясковец",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Мадан",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Маджарово",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Малко Търново",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Мартен",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Мездра",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Мелник",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Меричлери",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Мизия",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Момин проход",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Момчилград",
                            Region = "Кърджали"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Монтана",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Мъглиж",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Неделино",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Несебър",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Николаево",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Никопол",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Нова Загора",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Нови Искър",
                            Region = "София град"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Нови пазар",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Обзор",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Омуртаг",
                            Region = "Търговище"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Опака",
                            Region = "Търговище"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Оряхово",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Павел баня",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Павликени",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Пазарджик",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Панагюрище",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Перник",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Перущица",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Петрич",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Пещера",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Пирдоп",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Плачковци",
                            Region = "Габрово"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Плевен",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Плиска",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Пловдив",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Полски Тръмбеш",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Поморие",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Попово",
                            Region = "Търговище"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Пордим",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Правец",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Приморско",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Провадия",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Първомай",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Раднево",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Радомир",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Разград",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Разлог",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Ракитово",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Раковски",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Рила",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Роман",
                            Region = "Враца"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Рудозем",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Русе",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Садово",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Самоков",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Сандански",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Сапарева баня",
                            Region = "Кюстендил"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Свети Влас",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Свиленград",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Свищов",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Своге",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Севлиево",
                            Region = "Габрово"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Сеново",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Септември",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Силистра",
                            Region = "Силистра"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Симеоновград",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Симитли",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Славяново",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Сливен",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Сливница",
                            Region = "Софийска"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Сливо поле",
                            Region = "Русе"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Смолян",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Смядово",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Созопол",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Сопот",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 217,
                            Name = "София",
                            Region = "София град"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Средец",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Стамболийски",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Стара Загора",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Стражица",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Стралджа",
                            Region = "Ямбол"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Стрелча",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Суворово",
                            Region = "Варна"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Сунгурларе",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Сухиндол",
                            Region = "Велико Търново"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Съединение",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Сърница",
                            Region = "Пазарджик"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Твърдица",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Тервел",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Тетевен",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Тополовград",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Троян",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Трън",
                            Region = "Перник"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Тръстеник",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Трявна",
                            Region = "Габрово"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Тутракан",
                            Region = "Силистра"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Търговище",
                            Region = "Търговище"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Угърчин",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Хаджидимово",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Харманли",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Хасково",
                            Region = "Хасково"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Хисаря",
                            Region = "Пловдив"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Цар Калоян",
                            Region = "Разград"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Царево",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Чепеларе",
                            Region = "Смолян"
                        },
                        new
                        {
                            Id = 247,
                            Name = "Червен бряг",
                            Region = "Плевен"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Черноморец",
                            Region = "Бургас"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Чипровци",
                            Region = "Монтана"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Чирпан",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Шабла",
                            Region = "Добрич"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Шивачево",
                            Region = "Сливен"
                        },
                        new
                        {
                            Id = 253,
                            Name = "Шипка",
                            Region = "Стара Загора"
                        },
                        new
                        {
                            Id = 254,
                            Name = "Шумен",
                            Region = "Шумен"
                        },
                        new
                        {
                            Id = 255,
                            Name = "Ябланица",
                            Region = "Ловеч"
                        },
                        new
                        {
                            Id = 256,
                            Name = "Якоруда",
                            Region = "Благоевград"
                        },
                        new
                        {
                            Id = 257,
                            Name = "Ямбол",
                            Region = "Ямбол"
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation.");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The image of the news article.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("News article name.");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The news article's text.");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");

                    b.HasComment("News article");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Name of the subject.");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnType("int")
                        .HasComment("Type of the subject.");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("Subjects");

                    b.HasComment("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("796e81b0-19bb-49eb-b3d3-fa28611953c5"),
                            Name = "Математика",
                            SubjectTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("f9caa58d-cc09-493f-a63a-8e9026f001b7"),
                            Name = "Български език",
                            SubjectTypeId = 2
                        },
                        new
                        {
                            Id = new Guid("d911612e-e4ff-49a7-b84a-be8bf7ef2657"),
                            Name = "Английски език",
                            SubjectTypeId = 2
                        },
                        new
                        {
                            Id = new Guid("29c95f37-0968-4859-b363-ebba8627cf79"),
                            Name = "Информационни технологии",
                            SubjectTypeId = 3
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Subject type.");

                    b.HasKey("Id");

                    b.ToTable("SubjectTypes");

                    b.HasComment("Subject type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Academic"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Language"
                        },
                        new
                        {
                            Id = 3,
                            Type = "IT"
                        });
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Name of the training.");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int")
                        .HasComment("Type of the training.");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Trainings");

                    b.HasComment("Trainings");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Training type.");

                    b.HasKey("Id");

                    b.ToTable("TrainingTypes");

                    b.HasComment("Training type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Air sport"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Combat sport"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourseFilterBadge", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.FilterBadge", null)
                        .WithMany()
                        .HasForeignKey("FilterBadgesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUserSubject", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUsersSubjects")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.Subject", "Subject")
                        .WithMany("ApplicationUsersSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUserTraining", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUsersTrainings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.Training", "Training")
                        .WithMany("ApplicationUsersTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.BlogComment", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", "Author")
                        .WithMany("BlogComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.BlogPost", "BlogPost")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Course", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.CourseType", "CourseType")
                        .WithMany("Courses")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CourseType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Subject", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectType");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Training", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.TrainingType", "TrainingType")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LessonsBg.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUsersSubjects");

                    b.Navigation("ApplicationUsersTrainings");

                    b.Navigation("BlogComments");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.BlogPost", b =>
                {
                    b.Navigation("BlogComments");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.CourseType", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Subject", b =>
                {
                    b.Navigation("ApplicationUsersSubjects");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.Training", b =>
                {
                    b.Navigation("ApplicationUsersTrainings");
                });

            modelBuilder.Entity("LessonsBg.Core.Data.Models.TrainingType", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
